baseURL = "https://xiaoshan1994.github.io/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Kai Li"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
