[en]
title = "My blog"
weight = 1
LanguageName = "EN"
contentDir = "content/english"

[cn]
title = "我的博客"
description = "莱顿大学环境科学在读博士"
contentDir = "content/chinese" 
weight = 2
LanguageName = "CN"
