  [[main]]
  name = "博文"
  identifier = "home"
  weight = 100
  url = "/cn"

  [[main]]
  name = "发布日志"
  weight = 200
  identifier = "posts"
  url = "/cn/post"

  [[main]]
  name = "关于"
  weight = 300
  identifier = "about"
  url = "/cn/about"

  [[main]]
  name = "联系"
  weight = 400
  identifier = "contact"
  url = "/cn/contact"
