title = "Blog of Kai"
author = "Kai Li"
copyright = "2020-2021"
description = """Kai Li (李锴)
Leiden University
PhD candidate of Environmental Sciences"""
images = ["images/site_image.png"]
profilePicture = "images/profile.png"
favicon = "favicons/"
mainSections = ["post"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"


[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fas fa-university"
title = "university"
url = "https://www.universiteitleiden.nl/en/staffmembers/1/kai-li#tab-1"

[[socialIcons]]
icon = "fab fa-google"
title = "google"
url = "https://scholar.google.com/citations?user=JcZReB8AAAAJ&hl=zh-CN"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/xiaoshan1994"

[[socialIcons]]
icon = "fab fa-twitter-square"
title = "twitter"
url = "https://twitter.com/xiaoshan1994"

[[socialIcons]]
icon = "fab fa-facebook-square"
title = "facebook"
url = "https://www.facebook.com/profile.php?id=100063897362757"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:k.li@cml.leidenuniv.nl"
