baseURL = "https://xiaoshan1994.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "anatole"

[params]
title = "Kai Li (李锴)"
author = "Kai Li"
description = """PhD candidate in Environmental Sciences at Leiden University
k.li@cml.leidenuniv.nl
Blogging form Leiden since 2021
"""
favicon = "favicons/"
profilePicture = "images/Kai_profile2.png"
keywords = ""
doNotLoadAnimations = true # Animations are loaded by default
disableThemeSwitcher = true # Theme switcher is enabled by default
contentratio = 0.7
readMore = true

[Languages]
  [Languages.en]
  title = "My blog"
  weight = 1
  LanguageName = "EN"

  [Languages.cn]
  title = "我的博客"
  description = "Ich bin Jane"
  weight = 2
  LanguageName = "CN"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"


## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/lxndrblz/anatole/"

[[socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mail@example.com"
