baseURL = "https://xiaoshan1994.github.io/"
languageCode = "en-us"
title = "Website of kaili"
theme = "anatole"

[params]

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"
[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mail@example.com"

title = "Kai Li (李锴)"
author = "Kai Li"
description = """PhD candidate in Environmental Sciences at Leiden University
k.li@cml.leidenuniv.nl
"""
favicon = "favicons/"
profilePicture = "images/Kai_profile2.png"
keywords = ""

contentratio = 0.7
readMore = true

[Languages]
  [Languages.en]
  title = "My blog"
  weight = 1
  LanguageName = "EN"

  [Languages.cn]
  title = "我的博客"
  description = "Ich bin Jane"
  weight = 2
  LanguageName = "CN"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"



