baseURL = "https://xiaoshan1994.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "anatole"

[params]
title = "Kai Li"
author = "Kai Li"
description = "PhD candidate in Environmental Sciences"
profilePicture = "images/Kai_profile.jpg"
