baseURL = "https://xiaoshan1994.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "anatole"

[params]
title = "Kai Li (李锴)"
author = "Kai Li"
description = """PhD candidate in Environmental Sciences at Leiden University
k.li@cml.leidenuniv.nl
Blogging form Leiden since 2021
"""
profilePicture = "images/Kai_profile2.png"
keywords = ""
favicon = "favicons/klicon"
